on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools aerofiles shapely
      - name: run check-consistency script
        # This is a false positive. Stuttgart is touching itself, but is OK.
        run: |
          python bin/check-consistency.py source/airspace_germany.txt --errors-only --ignore-errors 'error: Invalid Polygon for Stuttgart 128.950:D (4500ft MSL-FL100)'
        
