on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: tree
      - run: date >> README.md
      - run: |
          git config --global user.name "bubeck"
          git config --global user.email "tilmann@bubecks.de"
          git commit -a -m "update to new version from internet"
          git push
          # git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
