on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bin/download-airspace-germany.sh
