on:
  schedule:
    - cron: '50 23 * * *'
  workflow_dispatch:

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run download-airspace-germany script
        run: bin/download-airspace-germany.sh
      - name: Commit files
        run: |
          git config user.email "workflow@github.com"
          git config user.name  "GitHub Workflow"
          git add -A
          now=$(date --iso-8601)
          git commit -m "Updated to $now from upstream by download-airspace-germany.sh" || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
