on:
  schedule:
    - cron: '50 23 * * *'

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.email "workflow@github.com"
          git config user.name  "GitHub Workflow"
          bin/download-airspace-germany.sh
