on:
  schedule:
    - cron: '50 23 * * *'

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.email "tilmann@bubecks.de"
          git config user.name  "Tilmann Bubeck"
          bin/download-airspace-germany.sh
